import {MigrationInterface, QueryRunner} from "typeorm";

export class into1730997426192 implements MigrationInterface {
    name = 'into1730997426192'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "attendance" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "updatedBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" character varying NOT NULL, "date" character varying, "clockIn" character varying, "clockOut" character varying, "latitude" character varying, "longitude" character varying, CONSTRAINT "PK_ee0ffe42c1f1a01e72b725c0cb2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_466e85b813d871bfb693f44352" ON "attendance" ("userId") `);
        await queryRunner.query(`CREATE TABLE "permission" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "updatedBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "resource" character varying(100) NOT NULL, "description" character varying NOT NULL, "path" character varying NOT NULL, "method" character varying(20) NOT NULL DEFAULT 'get', "isDefault" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_b690135d86d59cc689d465ac952" UNIQUE ("description"), CONSTRAINT "PK_3b8b97af9d9d8807e41e6f48362" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b690135d86d59cc689d465ac95" ON "permission" ("description") `);
        await queryRunner.query(`CREATE TABLE "role" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "updatedBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying(100) NOT NULL, "description" character varying NOT NULL, CONSTRAINT "UQ_ae4578dcaed5adff96595e61660" UNIQUE ("name"), CONSTRAINT "UQ_ae4578dcaed5adff96595e61660" UNIQUE ("name"), CONSTRAINT "PK_b36bcfe02fc8de3c57a8b2391c2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_profile_department_enum" AS ENUM('operations', 'accounts', 'administration')`);
        await queryRunner.query(`CREATE TYPE "public"."user_profile_bloodgroup_enum" AS ENUM('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-')`);
        await queryRunner.query(`CREATE TYPE "public"."user_profile_maritalstatus_enum" AS ENUM('single', 'married', 'divorced', 'widowed')`);
        await queryRunner.query(`CREATE TYPE "public"."user_profile_gender_enum" AS ENUM('male', 'female')`);
        await queryRunner.query(`CREATE TYPE "public"."user_profile_taxcalculation_enum" AS ENUM('single_assessee', 'couple_assessees')`);
        await queryRunner.query(`CREATE TABLE "user_profile" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "updatedBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "department" "public"."user_profile_department_enum", "location" character varying(100), "bloodGroup" "public"."user_profile_bloodgroup_enum", "maritalStatus" "public"."user_profile_maritalstatus_enum", "gender" "public"."user_profile_gender_enum", "taxCalculation" "public"."user_profile_taxcalculation_enum", "panNo" character varying(15), "permanentAddressCountry" character varying(100), "permanentAddressState" character varying(100), "permanentAddressDistrict" character varying(100), "permanentAddressLocalJurisdiction" character varying(100), "permanentAddressWardNo" character varying(10), "permanentAddressLocality" character varying(100), "temporaryAddressCountry" character varying(100), "temporaryAddressState" character varying(100), "temporaryAddressDistrict" character varying(100), "temporaryAddressLocalJurisdiction" character varying(100), "temporaryAddressWardNo" character varying(10), "temporaryAddressLocality" character varying(100), "guardianName" character varying(100), "guardianRelation" character varying(50), "guardianContact" character varying(15), "contactNo" character varying(15), "alternateContactNo" character varying(15), "personalEmail" character varying(254), "casualLeaves" integer NOT NULL DEFAULT '0', "examLeaves" integer NOT NULL DEFAULT '0', "maternityLeaves" integer NOT NULL DEFAULT '0', "paternityLeaves" integer NOT NULL DEFAULT '0', "otherLeaves" integer NOT NULL DEFAULT '0', "pf" boolean NOT NULL DEFAULT false, "hourlyCostRate" double precision NOT NULL DEFAULT '0', "publicHolidayAllowance" double precision NOT NULL DEFAULT '0', "userId" uuid, CONSTRAINT "UQ_282ad1dd8cfe8d0b89ca6c96a94" UNIQUE ("panNo"), CONSTRAINT "PK_f44d0cd18cfd80b0fed7806c3b7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_contract" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "updatedBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "filename" character varying(100), "documentFile" character varying, "userId" uuid, CONSTRAINT "PK_db82cc890300a2f5e47afd01318" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_bank_detail" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "updatedBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "bankName" character varying(100), "bankBranch" character varying(100), "accountNo" character varying(20), "documentFile" character varying, "userId" uuid, CONSTRAINT "PK_5aa4e921201c1e9c89b0bc94b03" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_training" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "updatedBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "institute" character varying(100), "designationOfCourse" character varying(100), "year" integer, "documentFile" character varying, "userId" uuid, CONSTRAINT "PK_d9e0183d7238191e94b862cf4d6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_document_documenttype_enum" AS ENUM('citizenship', 'passport', 'driving_license', 'pan_no', 'membership', 'others')`);
        await queryRunner.query(`CREATE TABLE "user_document" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "updatedBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "documentType" "public"."user_document_documenttype_enum", "identificationNo" character varying(50), "dateOfIssue" date, "placeOfIssue" character varying(100), "documentFile" character varying, "userId" uuid, CONSTRAINT "PK_18a41ed5aafb9732cfa62c8debd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."worklog_status_enum" AS ENUM('open', 'rejected', 'approved', 'pending')`);
        await queryRunner.query(`CREATE TABLE "worklog" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "updatedBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "description" text, "startTime" TIMESTAMP, "endTime" TIMESTAMP, "status" "public"."worklog_status_enum" NOT NULL DEFAULT 'open', "approvedBy" character varying, "userId" uuid NOT NULL, "projectId" uuid, "taskId" uuid, CONSTRAINT "PK_fec48929bbea5f702c38d022b3c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "project" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "updatedBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying(100) NOT NULL, "description" text NOT NULL, "status" character varying(20) NOT NULL, "natureOfWork" character varying(30) NOT NULL, "fiscalYear" integer NOT NULL, "startingDate" date NOT NULL, "endingDate" date NOT NULL, "projectLeadId" uuid, CONSTRAINT "PK_4d68b1358bb5b766d3e78f32f57" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "task_template" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "updatedBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying(100) NOT NULL, "description" text, "groupId" uuid, CONSTRAINT "UQ_1eb4288f2a64f5fe9b27da054cd" UNIQUE ("name"), CONSTRAINT "PK_b250e915df905dbe641647c8fac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "task_group" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "updatedBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "description" text, CONSTRAINT "PK_465a127df1ace09f377dd2eef6f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."task_status_enum" AS ENUM('open', 'in_progress', 'done')`);
        await queryRunner.query(`CREATE TABLE "task" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "updatedBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "tcode" character varying, "description" text, "dueDate" TIMESTAMP, "status" "public"."task_status_enum" DEFAULT 'open', "managerId" uuid, "projectId" uuid, "parentTaskId" uuid, "groupId" uuid, CONSTRAINT "UQ_20f1f21d6853d9d20d501636ebd" UNIQUE ("name"), CONSTRAINT "PK_fb213f79ee45060ba925ecd576e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notification" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "updatedBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "message" character varying NOT NULL, "type" character varying, "link" character varying, "isRead" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_705b6c7cdf9b2c2ff7ac7872cb7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "updatedBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "username" character varying NOT NULL, "email" character varying NOT NULL, "password" character varying, "name" character varying NOT NULL, "phoneNumber" character varying, "avatar" character varying, "status" character varying NOT NULL, "token" character varying, "tokenValidityDate" TIMESTAMP NOT NULL DEFAULT now(), "salt" character varying NOT NULL, "twoFASecret" character varying, "twoFAThrottleTime" TIMESTAMP NOT NULL DEFAULT now(), "isTwoFAEnabled" boolean NOT NULL DEFAULT false, "roleId" uuid NOT NULL, CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_78a916df40e02a9deb1c4b75ed" ON "user" ("username") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e12875dfb3b1d92d7d7c5377e2" ON "user" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_065d4d8f3b5adb4a08841eae3c" ON "user" ("name") `);
        await queryRunner.query(`CREATE TABLE "management_team_member" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "updatedBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying(100) NOT NULL, "designation" character varying(100) NOT NULL, "mobileNo" character varying(15), "telephoneNo" character varying(15), "email" character varying, "extNo" character varying(10), "department" character varying(100), "customerId" uuid, CONSTRAINT "PK_5380e31bd7e2ea17629dbff3ebe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "other_important_info" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "updatedBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "particular" character varying(200) NOT NULL, "description" text, "attachment" text, "customerId" uuid, CONSTRAINT "PK_dd680e0ada786d608df444a6d15" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."registration_and_license_frequencyofrenewal_enum" AS ENUM('every_year', 'every_3_years', 'every_5_years', 'more_than_5_years', 'renewal_not_required')`);
        await queryRunner.query(`CREATE TABLE "registration_and_license" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "updatedBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "statutoryAuthority" character varying(100), "registrationLicenseNo" character varying(100), "dateOfIssue" date, "validDate" date, "frequencyOfRenewal" "public"."registration_and_license_frequencyofrenewal_enum", "registrationLicenseAttachment" text, "customerId" uuid, CONSTRAINT "PK_f57b3fe3fb1766299d3a5f66786" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."customer_status_enum" AS ENUM('active', 'suspended', 'archive')`);
        await queryRunner.query(`CREATE TYPE "public"."customer_legalstatus_enum" AS ENUM('private_limited', 'public_limited', 'partnership', 'proprietorship', 'natural_person', 'i_ngo', 'cooperative', 'government_soe', 'others')`);
        await queryRunner.query(`CREATE TYPE "public"."customer_businesssize_enum" AS ENUM('micro', 'cottage', 'small', 'medium', 'large', 'not_applicable')`);
        await queryRunner.query(`CREATE TYPE "public"."customer_industrynature_enum" AS ENUM('banking_finance', 'capital_market_broking', 'insurance', 'energy_mining_mineral', 'manufacturing', 'agriculture_forestry', 'construction_real_estate', 'travel_tourism', 'research_development', 'transportation_logistics_management', 'information_transmission_communication', 'aviation', 'computer_electronics', 'trading_of_goods', 'personal_service', 'business_related_service', 'others')`);
        await queryRunner.query(`CREATE TABLE "customer" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "updatedBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying(100) NOT NULL, "panNo" character varying(15) NOT NULL, "registeredDate" date NOT NULL DEFAULT ('now'::text)::date, "status" "public"."customer_status_enum" NOT NULL DEFAULT 'active', "country" character varying(100) NOT NULL, "state" character varying(100) NOT NULL, "district" character varying(100) NOT NULL, "localJurisdiction" character varying(100) NOT NULL, "wardNo" character varying(10), "locality" character varying(100) NOT NULL, "legalStatus" "public"."customer_legalstatus_enum" NOT NULL, "businessSize" "public"."customer_businesssize_enum" NOT NULL, "industryNature" "public"."customer_industrynature_enum" NOT NULL, "telephoneNo" character varying(15), "mobileNo" character varying(15), "email" character varying, "website" character varying, "webPortal" character varying, "loginUser" character varying(100), "password" character varying(100), CONSTRAINT "PK_a7a13f4cacb744524e44dfdad32" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "board_member" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "updatedBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying(100) NOT NULL, "designation" character varying(100) NOT NULL, "mobileNo" character varying(15), "telephoneNo" character varying(15), "email" character varying, "extNo" character varying(10), "customerId" uuid, CONSTRAINT "PK_c27bedbf846391cf1af5e4a74d1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "email_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "updatedBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "title" character varying NOT NULL, "slug" character varying NOT NULL, "sender" character varying NOT NULL, "subject" character varying NOT NULL, "body" character varying NOT NULL, "isDefault" boolean NOT NULL, CONSTRAINT "PK_06c564c515d8cdb40b6f3bfbbb4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_4d77a74e85c275da60f4badf83" ON "email_templates" ("title") `);
        await queryRunner.query(`CREATE TABLE "refresh_token" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "ip" character varying NOT NULL, "userAgent" character varying NOT NULL, "browser" character varying, "os" character varying, "isRevoked" boolean NOT NULL, "expires" TIMESTAMP NOT NULL, CONSTRAINT "PK_b575dd3c21fb0831013c909e7fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_192c36a5937bf5eeb9de99290b" ON "refresh_token" ("browser") `);
        await queryRunner.query(`CREATE INDEX "IDX_cbf62122e9f9d90ecad419d49f" ON "refresh_token" ("os") `);
        await queryRunner.query(`CREATE TABLE "user_education" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdBy" character varying, "updatedBy" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "universityCollege" character varying(100), "faculty" character varying(100), "yearOfPassing" integer, "placeOfIssue" character varying(100), "documentFile" character varying, "userId" uuid, CONSTRAINT "PK_a08c404d196df11dc034f077cf3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role_permission" ("roleId" uuid NOT NULL, "permissionId" uuid NOT NULL, CONSTRAINT "PK_b42bbacb8402c353df822432544" PRIMARY KEY ("roleId", "permissionId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e3130a39c1e4a740d044e68573" ON "role_permission" ("roleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_72e80be86cab0e93e67ed1a7a9" ON "role_permission" ("permissionId") `);
        await queryRunner.query(`CREATE TABLE "user_notification" ("notificationId" uuid NOT NULL, "userId" uuid NOT NULL, CONSTRAINT "PK_766785a5a35127ae6570088aa2d" PRIMARY KEY ("notificationId", "userId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_680af16b67e94e2cb693b9e903" ON "user_notification" ("notificationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_dce2a8927967051c447ae10bc8" ON "user_notification" ("userId") `);
        await queryRunner.query(`CREATE TABLE "task_user" ("taskId" uuid NOT NULL, "userId" uuid NOT NULL, CONSTRAINT "PK_dd5a20f7313af9581ab8c30cfc6" PRIMARY KEY ("taskId", "userId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ff099dc6756bfef736ebe18ea9" ON "task_user" ("taskId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0f500c19a4a119f22a82c9b364" ON "task_user" ("userId") `);
        await queryRunner.query(`CREATE TABLE "user_project" ("projectId" uuid NOT NULL, "userId" uuid NOT NULL, CONSTRAINT "PK_2a37107e0b3bdb06b4920a64bbc" PRIMARY KEY ("projectId", "userId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cb5415b5e54f476329451212e9" ON "user_project" ("projectId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b88a18e4faeea3bce60d70a4ae" ON "user_project" ("userId") `);
        await queryRunner.query(`ALTER TABLE "user_profile" ADD CONSTRAINT "FK_51cb79b5555effaf7d69ba1cff9" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_contract" ADD CONSTRAINT "FK_30d5ee0e82f507af30a0125fe1d" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_bank_detail" ADD CONSTRAINT "FK_474450ce7e9d209ced1ca799cd0" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_training" ADD CONSTRAINT "FK_61bd1734ac31947fc6691824600" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_document" ADD CONSTRAINT "FK_bea6ff5b6ea0d461a438a2e837c" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "worklog" ADD CONSTRAINT "FK_29ddf4753d785e2c3ab27e5e793" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "worklog" ADD CONSTRAINT "FK_e2e028b3633a09d7b4a6d84acaf" FOREIGN KEY ("projectId") REFERENCES "project"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "worklog" ADD CONSTRAINT "FK_d4fbb3602e6b7f826d2d093b5f4" FOREIGN KEY ("taskId") REFERENCES "task"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project" ADD CONSTRAINT "FK_594c870bd9cea3ac8bb9029d59d" FOREIGN KEY ("projectLeadId") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_template" ADD CONSTRAINT "FK_9e04e955dad3df841cea1b11c43" FOREIGN KEY ("groupId") REFERENCES "task_group"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task" ADD CONSTRAINT "FK_2b8c3133172a8004844ebd0b1a3" FOREIGN KEY ("managerId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task" ADD CONSTRAINT "FK_3797a20ef5553ae87af126bc2fe" FOREIGN KEY ("projectId") REFERENCES "project"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task" ADD CONSTRAINT "FK_8bf6d736c49d48d91691ea0dfe5" FOREIGN KEY ("parentTaskId") REFERENCES "task"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task" ADD CONSTRAINT "FK_b8e1728a46f2cbb7b937011ae4f" FOREIGN KEY ("groupId") REFERENCES "task_group"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_c28e52f758e7bbc53828db92194" FOREIGN KEY ("roleId") REFERENCES "role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "management_team_member" ADD CONSTRAINT "FK_080790035368a55ce31cbc2b71d" FOREIGN KEY ("customerId") REFERENCES "customer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "other_important_info" ADD CONSTRAINT "FK_a9f50f6cf36d85d528d63082071" FOREIGN KEY ("customerId") REFERENCES "customer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "registration_and_license" ADD CONSTRAINT "FK_55237ba20183cc583e738e6a951" FOREIGN KEY ("customerId") REFERENCES "customer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "board_member" ADD CONSTRAINT "FK_fcf03dfc17993c29c377489301d" FOREIGN KEY ("customerId") REFERENCES "customer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_education" ADD CONSTRAINT "FK_98f09242a36729ef251819d19a4" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permission" ADD CONSTRAINT "FK_e3130a39c1e4a740d044e685730" FOREIGN KEY ("roleId") REFERENCES "role"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permission" ADD CONSTRAINT "FK_72e80be86cab0e93e67ed1a7a9a" FOREIGN KEY ("permissionId") REFERENCES "permission"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_notification" ADD CONSTRAINT "FK_680af16b67e94e2cb693b9e9033" FOREIGN KEY ("notificationId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_notification" ADD CONSTRAINT "FK_dce2a8927967051c447ae10bc8b" FOREIGN KEY ("userId") REFERENCES "notification"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_user" ADD CONSTRAINT "FK_ff099dc6756bfef736ebe18ea9a" FOREIGN KEY ("taskId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "task_user" ADD CONSTRAINT "FK_0f500c19a4a119f22a82c9b3640" FOREIGN KEY ("userId") REFERENCES "task"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_project" ADD CONSTRAINT "FK_cb5415b5e54f476329451212e9b" FOREIGN KEY ("projectId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_project" ADD CONSTRAINT "FK_b88a18e4faeea3bce60d70a4ae3" FOREIGN KEY ("userId") REFERENCES "project"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_project" DROP CONSTRAINT "FK_b88a18e4faeea3bce60d70a4ae3"`);
        await queryRunner.query(`ALTER TABLE "user_project" DROP CONSTRAINT "FK_cb5415b5e54f476329451212e9b"`);
        await queryRunner.query(`ALTER TABLE "task_user" DROP CONSTRAINT "FK_0f500c19a4a119f22a82c9b3640"`);
        await queryRunner.query(`ALTER TABLE "task_user" DROP CONSTRAINT "FK_ff099dc6756bfef736ebe18ea9a"`);
        await queryRunner.query(`ALTER TABLE "user_notification" DROP CONSTRAINT "FK_dce2a8927967051c447ae10bc8b"`);
        await queryRunner.query(`ALTER TABLE "user_notification" DROP CONSTRAINT "FK_680af16b67e94e2cb693b9e9033"`);
        await queryRunner.query(`ALTER TABLE "role_permission" DROP CONSTRAINT "FK_72e80be86cab0e93e67ed1a7a9a"`);
        await queryRunner.query(`ALTER TABLE "role_permission" DROP CONSTRAINT "FK_e3130a39c1e4a740d044e685730"`);
        await queryRunner.query(`ALTER TABLE "user_education" DROP CONSTRAINT "FK_98f09242a36729ef251819d19a4"`);
        await queryRunner.query(`ALTER TABLE "board_member" DROP CONSTRAINT "FK_fcf03dfc17993c29c377489301d"`);
        await queryRunner.query(`ALTER TABLE "registration_and_license" DROP CONSTRAINT "FK_55237ba20183cc583e738e6a951"`);
        await queryRunner.query(`ALTER TABLE "other_important_info" DROP CONSTRAINT "FK_a9f50f6cf36d85d528d63082071"`);
        await queryRunner.query(`ALTER TABLE "management_team_member" DROP CONSTRAINT "FK_080790035368a55ce31cbc2b71d"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_c28e52f758e7bbc53828db92194"`);
        await queryRunner.query(`ALTER TABLE "task" DROP CONSTRAINT "FK_b8e1728a46f2cbb7b937011ae4f"`);
        await queryRunner.query(`ALTER TABLE "task" DROP CONSTRAINT "FK_8bf6d736c49d48d91691ea0dfe5"`);
        await queryRunner.query(`ALTER TABLE "task" DROP CONSTRAINT "FK_3797a20ef5553ae87af126bc2fe"`);
        await queryRunner.query(`ALTER TABLE "task" DROP CONSTRAINT "FK_2b8c3133172a8004844ebd0b1a3"`);
        await queryRunner.query(`ALTER TABLE "task_template" DROP CONSTRAINT "FK_9e04e955dad3df841cea1b11c43"`);
        await queryRunner.query(`ALTER TABLE "project" DROP CONSTRAINT "FK_594c870bd9cea3ac8bb9029d59d"`);
        await queryRunner.query(`ALTER TABLE "worklog" DROP CONSTRAINT "FK_d4fbb3602e6b7f826d2d093b5f4"`);
        await queryRunner.query(`ALTER TABLE "worklog" DROP CONSTRAINT "FK_e2e028b3633a09d7b4a6d84acaf"`);
        await queryRunner.query(`ALTER TABLE "worklog" DROP CONSTRAINT "FK_29ddf4753d785e2c3ab27e5e793"`);
        await queryRunner.query(`ALTER TABLE "user_document" DROP CONSTRAINT "FK_bea6ff5b6ea0d461a438a2e837c"`);
        await queryRunner.query(`ALTER TABLE "user_training" DROP CONSTRAINT "FK_61bd1734ac31947fc6691824600"`);
        await queryRunner.query(`ALTER TABLE "user_bank_detail" DROP CONSTRAINT "FK_474450ce7e9d209ced1ca799cd0"`);
        await queryRunner.query(`ALTER TABLE "user_contract" DROP CONSTRAINT "FK_30d5ee0e82f507af30a0125fe1d"`);
        await queryRunner.query(`ALTER TABLE "user_profile" DROP CONSTRAINT "FK_51cb79b5555effaf7d69ba1cff9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b88a18e4faeea3bce60d70a4ae"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cb5415b5e54f476329451212e9"`);
        await queryRunner.query(`DROP TABLE "user_project"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0f500c19a4a119f22a82c9b364"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ff099dc6756bfef736ebe18ea9"`);
        await queryRunner.query(`DROP TABLE "task_user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dce2a8927967051c447ae10bc8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_680af16b67e94e2cb693b9e903"`);
        await queryRunner.query(`DROP TABLE "user_notification"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_72e80be86cab0e93e67ed1a7a9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e3130a39c1e4a740d044e68573"`);
        await queryRunner.query(`DROP TABLE "role_permission"`);
        await queryRunner.query(`DROP TABLE "user_education"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cbf62122e9f9d90ecad419d49f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_192c36a5937bf5eeb9de99290b"`);
        await queryRunner.query(`DROP TABLE "refresh_token"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4d77a74e85c275da60f4badf83"`);
        await queryRunner.query(`DROP TABLE "email_templates"`);
        await queryRunner.query(`DROP TABLE "board_member"`);
        await queryRunner.query(`DROP TABLE "customer"`);
        await queryRunner.query(`DROP TYPE "public"."customer_industrynature_enum"`);
        await queryRunner.query(`DROP TYPE "public"."customer_businesssize_enum"`);
        await queryRunner.query(`DROP TYPE "public"."customer_legalstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."customer_status_enum"`);
        await queryRunner.query(`DROP TABLE "registration_and_license"`);
        await queryRunner.query(`DROP TYPE "public"."registration_and_license_frequencyofrenewal_enum"`);
        await queryRunner.query(`DROP TABLE "other_important_info"`);
        await queryRunner.query(`DROP TABLE "management_team_member"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_065d4d8f3b5adb4a08841eae3c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e12875dfb3b1d92d7d7c5377e2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_78a916df40e02a9deb1c4b75ed"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TABLE "notification"`);
        await queryRunner.query(`DROP TABLE "task"`);
        await queryRunner.query(`DROP TYPE "public"."task_status_enum"`);
        await queryRunner.query(`DROP TABLE "task_group"`);
        await queryRunner.query(`DROP TABLE "task_template"`);
        await queryRunner.query(`DROP TABLE "project"`);
        await queryRunner.query(`DROP TABLE "worklog"`);
        await queryRunner.query(`DROP TYPE "public"."worklog_status_enum"`);
        await queryRunner.query(`DROP TABLE "user_document"`);
        await queryRunner.query(`DROP TYPE "public"."user_document_documenttype_enum"`);
        await queryRunner.query(`DROP TABLE "user_training"`);
        await queryRunner.query(`DROP TABLE "user_bank_detail"`);
        await queryRunner.query(`DROP TABLE "user_contract"`);
        await queryRunner.query(`DROP TABLE "user_profile"`);
        await queryRunner.query(`DROP TYPE "public"."user_profile_taxcalculation_enum"`);
        await queryRunner.query(`DROP TYPE "public"."user_profile_gender_enum"`);
        await queryRunner.query(`DROP TYPE "public"."user_profile_maritalstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."user_profile_bloodgroup_enum"`);
        await queryRunner.query(`DROP TYPE "public"."user_profile_department_enum"`);
        await queryRunner.query(`DROP TABLE "role"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b690135d86d59cc689d465ac95"`);
        await queryRunner.query(`DROP TABLE "permission"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_466e85b813d871bfb693f44352"`);
        await queryRunner.query(`DROP TABLE "attendance"`);
    }

}