/**
 * Default permissions for Administrator role.
 * Full access to administrative, management, and operational features.
 */
export const administratorDefaults: string[] = [
  "View task rankings",
  "Update task rankings",
  "Get all task super",
  "Add task super",
  "Edit task super",
  "Get task super by id",
  "Delete task super by id",
  "List active users",
  "View all user",
  "Store new user",
  "Update user by id",
  "Get user by id",
  "Delete user by id",
  "Get user profile",
  "Create user profile",
  "Update user profile",
  "Get user bank details",
  "Create user bank details",
  "Update user bank details",
  "Get user education details",
  "Create user education details",
  "Update user education details",
  "Get user documents",
  "Upload user documents",
  "Delete user document",
  "Update user status",
  "Edit user profile details",
  "Get user history",
  "View all role",
  "View role by id",
  "Store new role",
  "Update role by id",
  "Delete role by id",
  "View all permission",
  "Sync permission from config",
  "View permission by id",
  "Store new permission",
  "Update permission by id",
  "Delete permission by id",
  "View all email templates",
  "View email templates by id",
  "Store new email templates",
  "Update email templates by id",
  "Delete email templates by id",
  "View all Projects",
  "View project by id",
  "Store new project",
  "Update project by id",
  "Delete project by id",
  "Assign user to project",
  "Release user from project",
  "Update user assignment",
  "View project user assignments",
  "View user project assignments",
  "View user availability",
  "View user availability timeline",
  "View specific user availability",
  "View available users",
  "View users available by date",
  "View all tasks",
  "Add task",
  "Update task by id",
  "Get tasks by project id",
  "Add tasks in bulk",
  "Get all task template",
  "Edit task template",
  "Add task template",
  "Get task template",
  "Delete task template",
  "View all task types",
  "Create task type",
  "View task type by id",
  "Update task type",
  "Delete task type",
  "Get all task group",
  "Add task group",
  "Edit task group",
  "Get task group by id",
  "Delete task group by id",
  "Get worklogs by user",
  "Edit worklog",
  "Delete worklog",
  "Edit Attendance",
  "Get all Client",
  "Get Single Client",
  "Add Client",
  "Edit Client",
  "View client portal credentials",
  "View client portal credential by id",
  "Create client portal credential",
  "Update client portal credential",
  "Delete client portal credential",
  "View all portal credentials",
  "View portal credentials by id",
  "View portal credentials by customer",
  "Create portal credentials",
  "Update portal credentials",
  "Delete portal credentials",
  "View all billings",
  "View billing by id",
  "Store new billing",
  "Update billing by id",
  "Delete billing by id",
  "View all holidays",
  "View all leaves",
  "Update leave",
  "View all work hours",
  "Resolve work hours for user",
  "View all calendar events",
  "Calendar month view",
  "AD to BS conversion",
  "BS to AD conversion",
  "View all legal statuses",
  "Create legal status",
  "View legal status by id",
  "Update legal status",
  "Delete legal status",
  "View evaluations by project",
  "View evaluations by user"
];
