/**
 * Default permissions for Audit Junior role.
 * Operational permissions beyond baseline employee self-service.
 */
export const auditjuniorDefaults: string[] = [
  "Get all task super projects",
  "Get task super project by id",
  "Get task super projects by project id",
  "Get all task group projects",
  "Get task group project by id",
  "Get task group projects by project id",
  "Get task group projects by task super project id",
  "View task rankings",
  "Update task rankings",
  "Get all task super",
  "Add task super",
  "Edit task super",
  "Get task super by id",
  "Delete task super by id",
  "List active users",
  "View all user",
  "Get user by id",
  "Get user profile",
  "Get user bank details",
  "Get user education details",
  "Get user documents",
  "View all Projects",
  "View project by id",
  "View project user assignments",
  "View user availability",
  "View user availability timeline",
  "View specific user availability",
  "View available users",
  "View all tasks",
  "Get tasks by project id",
  "Edit worklog",
  "View all holidays",
  "View all leaves",
  "Update leave",
  "View all work hours",
  "Resolve work hours for user",
  "View all calendar events",
  "Calendar month view",
  "AD to BS conversion",
  "BS to AD conversion",
  "Create notice",
  "Upload notice image",
  "Get notice read statistics",
  "Update notice",
  "Delete notice",
  "View evaluations by project",
  "View evaluations by user"
];
