/**
 * Default permissions for Project Manager role.
 * Includes project oversight, task management, worklogs, leave approvals, and team management.
 */
export const projectmanagerDefaults: string[] = [
  "Get all task super projects",
  "Add task super project",
  "Edit task super project",
  "Get task super project by id",
  "Delete task super project by id",
  "Get task super projects by project id",
  "Get all task group projects",
  "Add task group project",
  "Edit task group project",
  "Get task group project by id",
  "Delete task group project by id",
  "Get task group projects by project id",
  "Get task group projects by task super project id",
  "View task rankings",
  "Update task rankings",
  "Get all task super",
  "Add task super",
  "Edit task super",
  "Get task super by id",
  "Delete task super by id",
  "List active users",
  "View all user",
  "Get user by id",
  "Get user profile",
  "Get user bank details",
  "Get user education details",
  "Get user documents",
  "View all Projects",
  "View project by id",
  "Mark project as completed",
  "Store new project",
  "Update project by id",
  "Delete project by id",
  "Assign user to project",
  "Release user from project",
  "Update user assignment",
  "View project user assignments",
  "View user project assignments",
  "View user availability",
  "View user availability timeline",
  "View specific user availability",
  "View available users",
  "View users available by date",
  "View all Project Types",
  "View Project Type by id",
  "Create Project Type",
  "Update Project Type",
  "Delete Project Type",
  "View all Project Type Groups",
  "View Project Type Group by id",
  "Create Project Type Group",
  "Update Project Type Group",
  "Delete Project Type Group",
  "View affected projects by Project Type",
  "View active affected projects by Project Type",
  "Migrate Project Type",
  "View all tasks",
  "Add task",
  "Update task by id",
  "Get tasks by project id",
  "Add tasks in bulk",
  "Get all task template",
  "Edit task template",
  "Add task template",
  "Get task template",
  "Delete task template",
  "Get all task group",
  "Add task group",
  "Edit task group",
  "Get task group by id",
  "Delete task group by id",
  "Get worklogs by user",
  "Edit worklog",
  "Get Attendance by ID",
  "Edit Attendance",
  "Delete Attendance by ID",
  "Get Attendance by User ID",
  "View all holidays",
  "Add holiday",
  "View holiday by id",
  "Update holiday",
  "Delete holiday",
  "Import holidays CSV",
  "Preview holidays CSV",
  "View all leaves",
  "Update leave",
  "Delete leave",
  "Approve leave by lead",
  "Approve leave by PM",
  "Approve leave by admin",
  "Reject leave",
  "View user leaves",
  "View all work hours",
  "Create work hour config",
  "View work hour by id",
  "Update work hour config",
  "Delete work hour config",
  "Resolve work hours for user",
  "View all calendar events",
  "Create calendar event",
  "View calendar event by id",
  "Update calendar event",
  "Delete calendar event",
  "AD to BS conversion",
  "BS to AD conversion",
  "Calendar month view",
  "View all leave types",
  "View active leave types",
  "Create leave type",
  "View leave type by id",
  "Update leave type",
  "Delete leave type",
  "Toggle leave type status",
  "View all legal statuses",
  "Create legal status",
  "View legal status by id",
  "Update legal status",
  "Delete legal status",
  "Get all Client",
  "Get Single Client",
  "Add Client",
  "Edit Client",
  "View client portal credentials",
  "View client portal credential by id",
  "Create client portal credential",
  "Update client portal credential",
  "Delete client portal credential",
  "View all task types",
  "View task type by id",
  "Create task type",
  "Update task type",
  "Delete task type",
  "View all todo task titles",
  "Create todo task title",
  "View todo task title by id",
  "Update todo task title",
  "Delete todo task title",
  "View all todo tasks",
  "View todo tasks by status",
  "View todo tasks assigned to user",
  "View todo tasks created by user",
  "View informed todo tasks",
  "View todo task by id",
  "Create todo task",
  "Update todo task",
  "Acknowledge todo task",
  "Mark todo task as pending",
  "Complete todo task",
  "Drop todo task",
  "Delete todo task",
  "Create project evaluation",
  "View all evaluations",
  "View evaluations by project",
  "View evaluations by user",
  "View single evaluation",
  "Update evaluation",
  "Delete evaluation",
  "Create project signoff",
  "View all signoffs",
  "View signoff by project",
  "View single signoff",
  "Update signoff",
  "Delete signoff"
];
